// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fft_fft,hls_ip_2020_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=23.017179,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=892,HLS_SYN_LUT=1739,HLS_VERSION=2020_1_1}" *)

module fft (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        real_in_TDATA,
        real_in_TKEEP,
        real_in_TLAST,
        imag_in_TDATA,
        imag_in_TKEEP,
        imag_in_TLAST,
        real_out_TDATA,
        real_out_TKEEP,
        real_out_TLAST,
        imag_out_TDATA,
        imag_out_TKEEP,
        imag_out_TLAST,
        real_in_TVALID,
        real_in_TREADY,
        imag_in_TVALID,
        imag_in_TREADY,
        real_out_TVALID,
        real_out_TREADY,
        imag_out_TVALID,
        imag_out_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
input  [63:0] real_in_TDATA;
input  [7:0] real_in_TKEEP;
input  [0:0] real_in_TLAST;
input  [63:0] imag_in_TDATA;
input  [7:0] imag_in_TKEEP;
input  [0:0] imag_in_TLAST;
output  [63:0] real_out_TDATA;
output  [7:0] real_out_TKEEP;
output  [0:0] real_out_TLAST;
output  [63:0] imag_out_TDATA;
output  [7:0] imag_out_TKEEP;
output  [0:0] imag_out_TLAST;
input   real_in_TVALID;
output   real_in_TREADY;
input   imag_in_TVALID;
output   imag_in_TREADY;
output   real_out_TVALID;
input   real_out_TREADY;
output   imag_out_TVALID;
input   imag_out_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] size;
wire    packComplex_U0_ap_start;
wire    packComplex_U0_ap_done;
wire    packComplex_U0_ap_continue;
wire    packComplex_U0_ap_idle;
wire    packComplex_U0_ap_ready;
wire    packComplex_U0_start_out;
wire    packComplex_U0_start_write;
wire   [127:0] packComplex_U0_dst_din;
wire    packComplex_U0_dst_write;
wire   [0:0] packComplex_U0_eos_din;
wire    packComplex_U0_eos_write;
wire    packComplex_U0_real_in_TREADY;
wire    packComplex_U0_imag_in_TREADY;
wire    unpackComplex_U0_ap_start;
wire    unpackComplex_U0_ap_done;
wire    unpackComplex_U0_ap_continue;
wire    unpackComplex_U0_ap_idle;
wire    unpackComplex_U0_ap_ready;
wire    unpackComplex_U0_dst_read;
wire    unpackComplex_U0_eos_read;
wire   [63:0] unpackComplex_U0_real_out_TDATA;
wire    unpackComplex_U0_real_out_TVALID;
wire   [7:0] unpackComplex_U0_real_out_TKEEP;
wire   [0:0] unpackComplex_U0_real_out_TLAST;
wire   [63:0] unpackComplex_U0_imag_out_TDATA;
wire    unpackComplex_U0_imag_out_TVALID;
wire   [7:0] unpackComplex_U0_imag_out_TKEEP;
wire   [0:0] unpackComplex_U0_imag_out_TLAST;
wire    ap_sync_continue;
wire    complex_stream_full_n;
wire   [127:0] complex_stream_dout;
wire    complex_stream_empty_n;
wire    eos_full_n;
wire   [0:0] eos_dout;
wire    eos_empty_n;
wire   [0:0] start_for_unpackComplex_U0_din;
wire    start_for_unpackComplex_U0_full_n;
wire   [0:0] start_for_unpackComplex_U0_dout;
wire    start_for_unpackComplex_U0_empty_n;
wire    unpackComplex_U0_start_full_n;
wire    unpackComplex_U0_start_write;

fft_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .size(size)
);

fft_packComplex packComplex_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(packComplex_U0_ap_start),
    .start_full_n(start_for_unpackComplex_U0_full_n),
    .ap_done(packComplex_U0_ap_done),
    .ap_continue(packComplex_U0_ap_continue),
    .ap_idle(packComplex_U0_ap_idle),
    .ap_ready(packComplex_U0_ap_ready),
    .start_out(packComplex_U0_start_out),
    .start_write(packComplex_U0_start_write),
    .dst_din(packComplex_U0_dst_din),
    .dst_full_n(complex_stream_full_n),
    .dst_write(packComplex_U0_dst_write),
    .eos_din(packComplex_U0_eos_din),
    .eos_full_n(eos_full_n),
    .eos_write(packComplex_U0_eos_write),
    .real_in_TDATA(real_in_TDATA),
    .real_in_TVALID(real_in_TVALID),
    .real_in_TREADY(packComplex_U0_real_in_TREADY),
    .real_in_TKEEP(real_in_TKEEP),
    .real_in_TLAST(real_in_TLAST),
    .imag_in_TDATA(imag_in_TDATA),
    .imag_in_TVALID(imag_in_TVALID),
    .imag_in_TREADY(packComplex_U0_imag_in_TREADY),
    .imag_in_TKEEP(imag_in_TKEEP),
    .imag_in_TLAST(imag_in_TLAST)
);

fft_unpackComplex unpackComplex_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(unpackComplex_U0_ap_start),
    .ap_done(unpackComplex_U0_ap_done),
    .ap_continue(unpackComplex_U0_ap_continue),
    .ap_idle(unpackComplex_U0_ap_idle),
    .ap_ready(unpackComplex_U0_ap_ready),
    .dst_dout(complex_stream_dout),
    .dst_empty_n(complex_stream_empty_n),
    .dst_read(unpackComplex_U0_dst_read),
    .eos_dout(eos_dout),
    .eos_empty_n(eos_empty_n),
    .eos_read(unpackComplex_U0_eos_read),
    .real_out_TDATA(unpackComplex_U0_real_out_TDATA),
    .real_out_TVALID(unpackComplex_U0_real_out_TVALID),
    .real_out_TREADY(real_out_TREADY),
    .real_out_TKEEP(unpackComplex_U0_real_out_TKEEP),
    .real_out_TLAST(unpackComplex_U0_real_out_TLAST),
    .imag_out_TDATA(unpackComplex_U0_imag_out_TDATA),
    .imag_out_TVALID(unpackComplex_U0_imag_out_TVALID),
    .imag_out_TREADY(imag_out_TREADY),
    .imag_out_TKEEP(unpackComplex_U0_imag_out_TKEEP),
    .imag_out_TLAST(unpackComplex_U0_imag_out_TLAST)
);

fft_fifo_w128_d2_S complex_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(packComplex_U0_dst_din),
    .if_full_n(complex_stream_full_n),
    .if_write(packComplex_U0_dst_write),
    .if_dout(complex_stream_dout),
    .if_empty_n(complex_stream_empty_n),
    .if_read(unpackComplex_U0_dst_read)
);

fft_fifo_w1_d64_S eos_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(packComplex_U0_eos_din),
    .if_full_n(eos_full_n),
    .if_write(packComplex_U0_eos_write),
    .if_dout(eos_dout),
    .if_empty_n(eos_empty_n),
    .if_read(unpackComplex_U0_eos_read)
);

fft_start_for_unpackComplex_U0 start_for_unpackComplex_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_unpackComplex_U0_din),
    .if_full_n(start_for_unpackComplex_U0_full_n),
    .if_write(packComplex_U0_start_write),
    .if_dout(start_for_unpackComplex_U0_dout),
    .if_empty_n(start_for_unpackComplex_U0_empty_n),
    .if_read(unpackComplex_U0_ap_ready)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign imag_in_TREADY = packComplex_U0_imag_in_TREADY;

assign imag_out_TDATA = unpackComplex_U0_imag_out_TDATA;

assign imag_out_TKEEP = unpackComplex_U0_imag_out_TKEEP;

assign imag_out_TLAST = unpackComplex_U0_imag_out_TLAST;

assign imag_out_TVALID = unpackComplex_U0_imag_out_TVALID;

assign packComplex_U0_ap_continue = 1'b1;

assign packComplex_U0_ap_start = 1'b1;

assign real_in_TREADY = packComplex_U0_real_in_TREADY;

assign real_out_TDATA = unpackComplex_U0_real_out_TDATA;

assign real_out_TKEEP = unpackComplex_U0_real_out_TKEEP;

assign real_out_TLAST = unpackComplex_U0_real_out_TLAST;

assign real_out_TVALID = unpackComplex_U0_real_out_TVALID;

assign start_for_unpackComplex_U0_din = 1'b1;

assign unpackComplex_U0_ap_continue = 1'b1;

assign unpackComplex_U0_ap_start = start_for_unpackComplex_U0_empty_n;

assign unpackComplex_U0_start_full_n = 1'b1;

assign unpackComplex_U0_start_write = 1'b0;

endmodule //fft
